CREATE TABLE INQUIRYTYPELINK(
	INQUIRY_IDX INT NOT NULL, 			/* 문의 테이블 주키(외래키)*/
	INQUIRYTYPE_IDX INT NOT NULL, 		/* 문의 타입 테이블 주키(외래키)*/
	FOREIGN KEY (INQUIRY_IDX) REFERENCES INQUIRY (INQUIRY_IDX)
	ON DELETE CASCADE,
	FOREIGN KEY (INQUIRYTYPE_IDX) REFERENCES INQUIRYTYPE (INQUIRYTYPE_IDX)
	ON DELETE CASCADE
);