CREATE TABLE INQUIRYFILE(
	INQUIRYFILE_IDX INT NOT NULL PRIMARY KEY AUTO_INCREMENT,		/* 문의파일 인덱스 */
	INQUIRY_IDX INT NOT NULL,										/* 문의 테이블 주키 (외래키) */
	INQUIRYFILE_NAME VARCHAR(60) NOT NULL,							/* 파일 이름 (서버 저장 후) */
	INQUIRYFILE_ORIGIN VARCHAR(100) NOT NULL,						/* 파일 이름 (서버 저장 전) */
	INQUIRYFILE_DIR VARCHAR(100) NOT NULL,							/* 파일 경로 */
	FOREIGN KEY (INQUIRY_IDX) REFERENCES INQUIRY (INQUIRY_IDX)
	ON DELETE CASCADE
);