CREATE TABLE RECRUITFILE(
	RECRUITFILE_IDX INT NOT NULL PRIMARY KEY AUTO_INCREMENT,		/* 채용공고 파일 인덱스 */
	RECRUIT_IDX INT NOT NULL,										/* 채용 테이블 주키 (외래키) */
	RECRUITFILE_DIR VARCHAR(100) NOT NULL,							/* 파일 경로 */
	RECRUITFILE_NAME VARCHAR(60) NOT NULL,							/* 파일 이름 */
	RECRUITFILE_TYPE CHAR(1) NOT NULL,								/* 파일 종류 이미지 = I, 기타 = O*/
	FOREIGN KEY (RECRUIT_IDX) REFERENCES RECRUIT (RECRUIT_IDX)
	ON DELETE CASCADE
);